#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      mkdir -p /var/log/boot
      exec > /var/log/boot/cloud-config.log 2>&1

      mkdir -p /home/rancher/backups
      cat <<EOF > /home/rancher/backup.sh
      #!/bin/sh
      export DATE=\$(date '+%s')
      export RANCHER_CONTAINER_NAME=rancher
      export RANCHER_VERSION=${rancher_version}

      docker stop \$RANCHER_CONTAINER_NAME
      docker create --volumes-from \$RANCHER_CONTAINER_NAME --name rancher-data-\$DATE rancher/rancher:\$RANCHER_VERSION
      docker run --volumes-from rancher-data-\$DATE -v \$PWD/backups:/backup busybox tar zcvf /backup/rancher-data-backup-"\$RANCHER_VERSION"-"\$DATE".tar.gz /var/lib/rancher
      docker start \$RANCHER_CONTAINER_NAME
      EOF

      cat <<EOF > /home/rancher/upgrade.sh
      #!/bin/sh
      export DATE=
      export RANCHER_CONTAINER_NAME=rancher
      export RANCHER_VERSION=${rancher_version}

      docker stop \$RANCHER_CONTAINER_NAME
      docker rename \$RANCHER_CONTAINER_NAME "\$RANCHER_CONTAINER_NAME"_\$(date '+%s')
      docker run -d --volumes-from rancher-data-\$DATE \
        --restart=unless-stopped \
        -p 80:80 -p 443:443 \
        rancher/rancher:\$RANCHER_VERSION \
        --acme-domain ${name}.${domain}
      EOF

      chown -R rancher:rancher /home/rancher
      export INSTANCE_ID=$(wget -qO- http://169.254.169.254/latest/meta-data/instance-id)
      wait-for-docker
      docker run -d --name rancher \
        --restart unless-stopped \
        -v /var/lib/rancher:/var/lib/rancher \
        -p 80:80 -p 443:443 \
        rancher/rancher:${rancher_version} \
        --acme-domain ${name}.${domain}
rancher:
  console: ubuntu
  docker:
    engine: ${docker_version}
    log_driver: "json-file"
    log_opts:
      max-file: "3"
      max-size: "100m"
      labels: "production"
  services_include:
    kernel-headers: true
